---
title: "Fukuoka COVID-19"
output: 
  flexdashboard::flex_dashboard:
    social: [ "menu" ]
    source_code: "https://github.com/kzktmr/FukuokaCovid19"
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
# ライブラリ
library(tidyr)
library(dplyr)
library(readr)
library(stringr)
library(lubridate)
library(flexdashboard)
library(plotly)

# データ
fn <- list.files("Data", "^data_.+csv$", full.names = TRUE) |> dplyr::last()
dat <- readr::read_csv(fn) 
dat_fuk <- dat |> filter(name == "per_sentinel", region == "福岡県") |> 
  mutate(year_week = str_glue("{year}_{sprintf('%02d', week)}"),
         growth = value / lag(value))
ambulance <- readr::read_csv("ambulance.csv") |> 
  mutate(year_week = str_glue("{year}_{sprintf('%02d', week)}")) |> 
  filter(year_week >= "2022_41") |> 
  mutate(city = factor(city, levels = c("福岡市消防局", "北九州市消防局")))
nurse <- readr::read_csv("nurse.csv") |> 
  filter(type %in% c("休んでいる看護職員の総数",
                     "うち、本人の感染以外を理由に休んでいる看護職員数")) |> 
  mutate(year_week = str_glue("{year}_{sprintf('%02d', week)}")) |> 
  filter(year_week >= "2022_41") |> 
  mutate(type = factor(type, levels = c("休んでいる看護職員の総数",
                     "うち、本人の感染以外を理由に休んでいる看護職員数")))
#
hline <- function(y = 0, color = "black") {
  list(
    type = "line",
    x0 = 0,
    x1 = 1,
    xref = "paper",
    y0 = y,
    y1 = y,
    line = list(color = color)
  )
}
```

Row
-------------------------------------

###

```{r}
plot_ly() |> add_bars(data = dat_fuk, x = ~year_week, y = ~value) |> 
  layout(title = '定点あたり報告数', 
         xaxis = list(title = NA), yaxis = list(title = NA))
```

### 

```{r}
plot_ly() |> add_lines(data = dat_fuk, x = ~year_week, y = ~growth) |> 
  layout(title = '定点あたり報告数前週比',
         xaxis = list(title = NA), yaxis = list(title = NA),
         shapes = list(hline(y = 1, color = "red")))
```


Row
-------------------------------------

### 

```{r}
plot_ly() |> 
  add_lines(data = ambulance, x = ~year_week, y = ~value, color = ~city) |> 
  layout(legend = list(x = 0.05, y = 0.95),
         xaxis = list(title = NA), yaxis = list(title = NA),
         title = '救急搬送困難事案件数')
```

### 

```{r}
plot_ly() |> 
  add_lines(data = nurse, x = ~year_week, y = ~value, color = ~type) |> 
  layout(legend = list(x = 0.05, y = 0.95),
         xaxis = list(title = NA), yaxis = list(title = NA),
         title = '重点医療機関における新型コロナウイルス感染症に関連して休んでいる看護職員数')
```